CONTIKI = /home/user/contiki
PROJECT_SOURCEFILES = BcpRoutingEngine.c BcpForwardingEngine.c mydebug.c

all: hello  

include $(CONTIKI)/Makefile.include
#CFLAGS  += -DNDEBUG     #comment out this line to ENABLE debugging statements
